In [10]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

# import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [11]:
import plotly.express as px
import plotly.graph_objects as go
from plotly.offline import offline, iplot
from IPython.display import display, HTML
import warnings
warnings.filterwarnings("ignore", category=FutureWarning, module="plotly")



pd.options.display.float_format = "{:,.1f}".format

In [12]:
def update_layout(title_font_size = 28, hover_font_size = 16, hover_bgcolor = "#45FFCA", showlegend = False):
    fig.update_layout(
        showlegend = showlegend,
        title = {
            "font" : {
                "size" :title_font_size,
                "family" :"tahoma"
            }
        },
        hoverlabel={
            "bgcolor": hover_bgcolor,
            "font_size": hover_font_size,
            "font_family": "tahoma"
        }
    )

# Load The Dataset

In [13]:
# ============================================================
# 📥 Load YouTube Dataset from Google Drive
# ============================================================

# Install gdown (run only once)
!pip install -q gdown

# Import required libraries
import gdown
import pandas as pd

# Google Drive File ID
file_id = "1s8SRMhY9_bWosHUiPLWsiBA-lbuS1_-v"

# Download dataset
url = f"https://drive.google.com/uc?id={file_id}"
gdown.download(url, "youtube_dataset.csv", quiet=False)

# Load the dataset
df = pd.read_csv("youtube_dataset.csv")

# Display basic information
print("=" * 50)
print("Dataset Loaded Successfully!")
print("=" * 50)

print("\nShape of Dataset:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

print("\nFirst 5 Rows:")
display(df.head())

print("\nRandom 10 Rows:")
display(df.sample(10))

Downloading...
From: https://drive.google.com/uc?id=1s8SRMhY9_bWosHUiPLWsiBA-lbuS1_-v
To: /content/youtube_dataset.csv
100%|██████████| 2.54M/2.54M [00:00<00:00, 165MB/s]

==================================================
Dataset Loaded Successfully!
==================================================

Shape of Dataset:
(22958, 6)

Column Names:
['Channel_Name', 'Title', 'Published_date', 'Views', 'Like_count', 'Comment_Count']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22958 entries, 0 to 22957
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Channel_Name    22958 non-null  object
 1   Title           22958 non-null  object
 2   Published_date  22958 non-null  object
 3   Views           22956 non-null  float64
 4   Like_count      22956 non-null  float64
 5   Comment_Count   22931 non-null  float64
dtypes: float64(3), object(3)
memory usage: 1.1+ MB

Missing Values:
Channel_Name       0
Title              0
Published_date     0
Views              2
Like_count         2
Comment_Count     27
dtype: int64

First 5 Rows:

,Channel_Name,Title,Published_date,Views,Like_count,Comment_Count
0,DeepLearningAI,Learn to build multi-agent systems with divers...,2024-06-06,"1,650.0","1,650.0",2.0
1,DeepLearningAI,New Course: AI Agents in LangGraph,2024-06-05,"2,472.0","2,472.0",1.0
2,DeepLearningAI,New course on agents! Enroll in AI Agentic Des...,2024-05-29,"3,140.0","3,140.0",5.0
3,DeepLearningAI,Learn to deploy AI models on edge devices like...,2024-05-28,"2,234.0","2,234.0",0.0
4,DeepLearningAI,New course with Qualcomm: Introduction to On-D...,2024-05-21,"2,987.0","2,987.0",6.0

Random 10 Rows:

,Channel_Name,Title,Published_date,Views,Like_count,Comment_Count
18247,codebasics,Collision Handling In Hash Table - Data Struct...,2020-03-22,"150,010.0","150,010.0",210.0
15288,sentdex,Scikit-Learn incorporation - Natural Language ...,2015-05-16,"65,441.0","65,441.0",94.0
5951,ExcelIsFun,Excel 2013 Statistical Analysis #20: Standard ...,2015-01-24,"27,522.0","27,522.0",32.0
10063,WsCube Tech,Interesting Internet Facts! #shorts,2022-07-21,"7,137.0","7,137.0",12.0
12496,WsCube Tech,How to use Social Blade to do Analytics - Inst...,2020-12-06,"10,905.0","10,905.0",7.0
9897,WsCube Tech,this Keyword in Java & How to Use | Java Tutor...,2022-09-01,"2,667.0","2,667.0",10.0
20937,freeCodeCamp.org,Web Workers — Outsource your JavaScript,2018-06-26,"6,445.0","6,445.0",7.0
4259,Kevin Stratvert,How to Live Stream Microsoft Teams Meeting to ...,2020-06-21,"127,141.0","127,141.0",92.0
13710,WsCube Tech,Functions in C | Library Function in C | funct...,2019-02-18,"5,933.0","5,933.0",8.0
20871,freeCodeCamp.org,The Five Ws of Atomic Design,2018-08-16,"12,430.0","12,430.0",8.0

In [14]:
# 📥 Load the YouTube dataset
df = pd.read_csv("/content/youtube_dataset.csv")

# 🎲 Display 10 random records from the dataset
df.sample(n=10)

,Channel_Name,Title,Published_date,Views,Like_count,Comment_Count
5123,ExcelIsFun,Free Excel Data Analysis Basics Course at YouT...,2020-02-07,"23,335.0","23,335.0",124.0
16558,Ken Jee,Uber Driver to Machine Learning Engineer in 9 ...,2020-07-16,"30,582.0","30,582.0",121.0
11,DeepLearningAI,New course with Comet: Prompt Engineering for ...,2024-04-29,"2,233.0","2,233.0",8.0
5847,ExcelIsFun,Excel Magic Trick 1216: Fraction Number Format...,2015-07-30,"4,188.0","4,188.0",15.0
21242,freeCodeCamp.org,"React, NextJS, CSS - Live Coding with Jesse",2017-07-11,"4,810.0","4,810.0",0.0
10940,WsCube Tech,How to MAKE & SET YouTube Channel Trailer? (Te...,2021-12-09,"49,485.0","49,485.0",40.0
1419,CampusX,K Nearest Neighbors Part 9 - Hyper-parameters,2019-10-29,"7,265.0","7,265.0",6.0
7178,ExcelIsFun,Excel Magic Trick 699: VLOOKUP Mixed Number & ...,2010-09-03,"66,673.0","66,673.0",20.0
14264,Chandoo,How to get web data into Excel (case study wit...,2019-10-09,"4,824.0","4,824.0",7.0
5211,ExcelIsFun,Excel Keyboard to Insert Sheet & Rename Sheet....,2019-07-17,"4,839.0","4,839.0",44.0

# Now, Let's Get a Quick Overview 🧐

In [15]:
df.shape

(22958, 6)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22958 entries, 0 to 22957
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Channel_Name    22958 non-null  object
 1   Title           22958 non-null  object
 2   Published_date  22958 non-null  object
 3   Views           22956 non-null  float64
 4   Like_count      22956 non-null  float64
 5   Comment_Count   22931 non-null  float64
dtypes: float64(3), object(3)
memory usage: 1.1+ MB

# Now, It's Time For Data Cleaning & Preprocessing🧐🔨

In [17]:
#as the null value are in the Views Like_count Comment_Count  we can replace it will 0
df=df.fillna(0)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22958 entries, 0 to 22957
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Channel_Name    22958 non-null  object
 1   Title           22958 non-null  object
 2   Published_date  22958 non-null  object
 3   Views           22958 non-null  float64
 4   Like_count      22958 non-null  float64
 5   Comment_Count   22958 non-null  float64
dtypes: float64(3), object(3)
memory usage: 1.1+ MB

In [19]:
df.dtypes

Channel_Name       object
Title              object
Published_date     object
Views             float64
Like_count        float64
Comment_Count     float64
dtype: object

In [20]:
df['Published_date'] = pd.to_datetime(df['Published_date'], format='%Y-%m-%d')

In [21]:
df['Views'] = df['Views'].astype('int64')
df['Like_count'] = df['Like_count'].astype('int64')
df['Comment_Count'] = df['Comment_Count'].astype('int64')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22958 entries, 0 to 22957
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Channel_Name    22958 non-null  object
 1   Title           22958 non-null  object
 2   Published_date  22958 non-null  datetime64[ns]
 3   Views           22958 non-null  int64
 4   Like_count      22958 non-null  int64
 5   Comment_Count   22958 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 1.1+ MB

# Now, Let's Dive Deeper Into Each Important Column 🌊🧐

<h3 style = "background-color: #111;
             padding: 15px;
             font: bold 22px arial;
             color: lightgreen;
             border: 2px solid lime;
             border-radius: 8px">
♠ Rating Column 👦 🧔</h3>

In [23]:
Channel = df["Channel_Name"].value_counts()
(Channel / df.shape[0] * 100).apply(lambda x: f"{x: 0.2f} %")

Channel_Name
WsCube Tech                     22.47 %
ExcelIsFun                      16.11 %
Krish Naik                       7.99 %
freeCodeCamp.org                 7.27 %
sentdex                          5.46 %
CampusX                          4.57 %
Guy in a Cube                    4.51 %
codebasics                       3.82 %
Kevin Stratvert                  3.72 %
Socratica                        2.88 %
Leila Gharani                    2.54 %
Tableau Tim                      2.21 %
Chandoo                          2.09 %
DeepLearningAI                   1.88 %
Kaggle                           1.66 %
Nicholas Renotte                 1.34 %
Alex The Analyst                 1.34 %
Ken Jee                          1.25 %
StatQuest with Josh Starmer      1.21 %
Tina Huang                       0.96 %
Luke Barousse                    0.69 %
Rob Mulla                        0.68 %
Ryan Nolan Data                  0.67 %
Darshil Parmar                   0.66 %
techTFQ                          0.59 %
Keith Galli                      0.39 %
Rishabh Mishra                   0.38 %
Thu Vu data analytics            0.37 %
Dataquest                        0.22 %
Andrej Karpathy                  0.07 %
Name: count, dtype: object

# Channel Name and Number of videos(%)

In [24]:
# Create the bar plot
fig = px.bar(
    data_frame=Channel.head(10),
    x=Channel.head(10).index,
    y=(Channel / sum(Channel) * 100).head(10),
    color=Channel.head(10).index,
    color_discrete_sequence=["#FF0060", "#45FFCA", "#45FFCA", "#293462", "#FF55BB", "#293462"],
    labels={"index": "Channel Name", "y": "(%)"},
    title="Channel Name and Number of videos(%)",
    text=Channel.head(10).apply(lambda x: f"{x / sum(Channel) * 100:0.2f}%"),
    template="plotly_dark"
)

# Update the layout
fig.update_layout(
    hoverlabel=dict(bgcolor="#111"),
    title_font=dict(size=24, color='lightgreen'),
    xaxis=dict(title='Channel Name'),
    yaxis=dict(title='Videos(%)'),
)

# Update traces
fig.update_traces(
    textfont={
        "family": "tahoma",
        "size": 13,
    },
    hovertemplate="Channel Name: %{x}<br>Videos: %{y:0.2f}%"
)

# Display the plot
iplot(fig)

<h3 style = "background-color: #111;
             padding: 15px;
             font: bold 22px arial;
             color: gold;
             border: 3px solid tomato;
             border-radius: 8px">
► From This Graph We Can Say that Ws cube tech uploads most videos !!!</h3>

# Number of Videos of data Science educators Through Years

In [25]:
view_by_year=df.groupby(df['Published_date'].dt.year)['Views'].agg('sum')
view_by_year

Published_date
2008     22022134
2009     27035684
2010     22467572
2011     16278454
2012     18713059
2013     26628638
2014     41098125
2015     39824091
2016     52527550
2017    110918957
2018    252950947
2019    357491113
2020    421882608
2021    500637257
2022    405691985
2023    230701146
2024     50743709
Name: Views, dtype: int64

In [26]:
fig = px.area(view_by_year,
            x = view_by_year.index,
            y =view_by_year,
            labels = {"index" :"Year", "y" :"View Counts"},
            line_shape="spline",
            color_discrete_sequence=["#FF0060"],
            title = "Views in Data Science Content Through Years ⌛",
            template="plotly_dark",
              markers="O",

       )


update_layout()

fig.update_traces(
    textfont = {
        "family": "tahoma",
         "size": 13,
    },
    hovertemplate= "Year: %{x}<br>View Counts: %{y:0.2s}"
)
iplot(fig)

In [27]:
year=df['Published_date'].dt.year.value_counts().sort_index()
year

Published_date
2008     366
2009     614
2010     489
2011     359
2012     442
2013     686
2014     502
2015     621
2016     649
2017    1129
2018    1146
2019    2042
2020    3177
2021    3738
2022    3429
2023    2419
2024    1150
Name: count, dtype: int64

In [28]:
fig = px.area(year,
        x = year.index,
        y =year,
        labels = {"index" :"Year", "y" :"Videos Counts"},
        line_shape="spline",
        color_discrete_sequence=["#45FFCA"],
        title = "Number of Videos of data Science educators Through Years 🗓️",
        template="plotly_dark",
       )


update_layout()
iplot(fig)

<h3 style = "background-color: #111;
             padding: 15px;
             font: bold 22px arial;
             color: red;
             border: 3px solid tomato;
             border-radius: 8px">
  Videos of data Science educators were highest in the year 2020-2022 probably beacuse of covid !!!</h3>

# Top 10 Data Science YouTube channels

In [29]:
df1= df.groupby('Channel_Name', as_index=False)['Views'].agg(['count', 'mean', 'sum'])
df1.columns = ['Channel_Name','video_count', 'view_mean', 'view_count']
df1

                   Channel_Name  video_count  view_mean  view_count
0              Alex The Analyst          307  114,871.2    35265444
1               Andrej Karpathy           15  690,405.2    10356078
2                       CampusX         1050   20,907.1    21952453
3                       Chandoo          479  100,542.6    48159907
4                Darshil Parmar          152   41,373.9     6288834
5                     Dataquest           50   41,937.0     2096849
6                DeepLearningAI          432   42,809.3    18493611
7                    ExcelIsFun         3698   41,834.8   154704922
8                 Guy in a Cube         1036   34,405.9    35644514
9                        Kaggle          380   11,207.7     4258920
10                  Keith Galli           89  170,584.2    15181994
11                      Ken Jee          287   31,390.1     9008964
12              Kevin Stratvert          854  491,454.7   419702350
13                   Krish Naik         1834   53,714.4    98512242
14                Leila Gharani          583  434,039.8   253045182
15                Luke Barousse          159  139,121.3    22120289
16             Nicholas Renotte          308   57,330.2    17657705
17               Rishabh Mishra           88  184,760.7    16258940
18                    Rob Mulla          157   74,002.4    11618374
19              Ryan Nolan Data          154    2,039.4      314062
20                    Socratica          661   89,974.0    59472846
21  StatQuest with Josh Starmer          278  236,140.1    65646950
22                  Tableau Tim          508    7,863.1     3994445
23        Thu Vu data analytics           86   91,346.9     7855837
24                   Tina Huang          220  142,059.9    31253178
25                  WsCube Tech         5158   56,255.7   290166978
26                   codebasics          876   97,570.3    85471551
27             freeCodeCamp.org         1669  432,369.5   721624649
28                      sentdex         1254   91,576.7   114837190
29                      techTFQ          136  122,410.1    16647771

In [30]:
df2 = df.groupby('Channel_Name', as_index=False)['Like_count'].agg(['mean', 'count', 'sum'])
df2.columns = ['Channel_Name','Like_mean', 'video_count', 'Like_count']
df2

                   Channel_Name  Like_mean  video_count  Like_count
0              Alex The Analyst  114,871.2          307    35265444
1               Andrej Karpathy  690,405.2           15    10356078
2                       CampusX   20,907.1         1050    21952453
3                       Chandoo  100,542.6          479    48159907
4                Darshil Parmar   41,373.9          152     6288834
5                     Dataquest   41,937.0           50     2096849
6                DeepLearningAI   42,809.3          432    18493611
7                    ExcelIsFun   41,834.8         3698   154704922
8                 Guy in a Cube   34,405.9         1036    35644514
9                        Kaggle   11,207.7          380     4258920
10                  Keith Galli  170,584.2           89    15181994
11                      Ken Jee   31,390.1          287     9008964
12              Kevin Stratvert  491,454.7          854   419702350
13                   Krish Naik   53,714.4         1834    98512242
14                Leila Gharani  434,039.8          583   253045182
15                Luke Barousse  139,121.3          159    22120289
16             Nicholas Renotte   57,330.2          308    17657705
17               Rishabh Mishra  184,760.7           88    16258940
18                    Rob Mulla   74,002.4          157    11618374
19              Ryan Nolan Data    2,039.4          154      314062
20                    Socratica   89,974.0          661    59472846
21  StatQuest with Josh Starmer  236,140.1          278    65646950
22                  Tableau Tim    7,863.1          508     3994445
23        Thu Vu data analytics   91,346.9           86     7855837
24                   Tina Huang  142,059.9          220    31253178
25                  WsCube Tech   56,255.7         5158   290166978
26                   codebasics   97,570.3          876    85471551
27             freeCodeCamp.org  432,369.5         1669   721624649
28                      sentdex   91,576.7         1254   114837190
29                      techTFQ  122,410.1          136    16647771

In [31]:
df3 = df.groupby('Channel_Name', as_index=False)['Comment_Count'].agg(['mean', 'count', 'sum'])
df3.columns = ['Channel_Name','Comment_mean', 'video_count', 'Comment_count']
df3

                   Channel_Name  Comment_mean  video_count  Comment_count
0              Alex The Analyst         178.0          307          54633
1               Andrej Karpathy         619.0           15           9285
2                       CampusX          38.3         1050          40234
3                       Chandoo          89.0          479          42617
4                Darshil Parmar          88.9          152          13510
5                     Dataquest          47.5           50           2375
6                DeepLearningAI          15.3          432           6600
7                    ExcelIsFun          40.6         3698         149979
8                 Guy in a Cube          41.9         1036          43357
9                        Kaggle           7.4          380           2805
10                  Keith Galli         176.4           89          15703
11                      Ken Jee          98.1          287          28143
12              Kevin Stratvert         382.6          854         326716
13                   Krish Naik          70.7         1834         129752
14                Leila Gharani         362.0          583         211057
15                Luke Barousse         190.2          159          30246
16             Nicholas Renotte         130.1          308          40060
17               Rishabh Mishra         349.4           88          30746
18                    Rob Mulla          83.8          157          13157
19              Ryan Nolan Data           7.5          154           1151
20                    Socratica          79.9          661          52827
21  StatQuest with Josh Starmer         337.6          278          93856
22                  Tableau Tim          11.2          508           5697
23        Thu Vu data analytics         111.6           86           9597
24                   Tina Huang         215.0          220          47291
25                  WsCube Tech          40.4         5158         208442
26                   codebasics          93.7          876          82091
27             freeCodeCamp.org         297.3         1669         496224
28                      sentdex         108.3         1254         135843
29                      techTFQ         174.6          136          23740

In [32]:
Channel_comparison = pd.concat([df1, df2[['Like_mean','Like_count']],df3[['Comment_mean','Comment_count']]],axis=1).query('video_count>20')
Channel_comparison

,Channel_Name,video_count,view_mean,view_count,Like_mean,Like_count,Comment_mean,Comment_count
0,Alex The Analyst,307,"114,871.2",35265444,"114,871.2",35265444,178.0,54633
2,CampusX,1050,"20,907.1",21952453,"20,907.1",21952453,38.3,40234
3,Chandoo,479,"100,542.6",48159907,"100,542.6",48159907,89.0,42617
4,Darshil Parmar,152,"41,373.9",6288834,"41,373.9",6288834,88.9,13510
5,Dataquest,50,"41,937.0",2096849,"41,937.0",2096849,47.5,2375
6,DeepLearningAI,432,"42,809.3",18493611,"42,809.3",18493611,15.3,6600
7,ExcelIsFun,3698,"41,834.8",154704922,"41,834.8",154704922,40.6,149979
8,Guy in a Cube,1036,"34,405.9",35644514,"34,405.9",35644514,41.9,43357
9,Kaggle,380,"11,207.7",4258920,"11,207.7",4258920,7.4,2805
10,Keith Galli,89,"170,584.2",15181994,"170,584.2",15181994,176.4,15703
11,Ken Jee,287,"31,390.1",9008964,"31,390.1",9008964,98.1,28143
12,Kevin Stratvert,854,"491,454.7",419702350,"491,454.7",419702350,382.6,326716
13,Krish Naik,1834,"53,714.4",98512242,"53,714.4",98512242,70.7,129752
14,Leila Gharani,583,"434,039.8",253045182,"434,039.8",253045182,362.0,211057
15,Luke Barousse,159,"139,121.3",22120289,"139,121.3",22120289,190.2,30246
16,Nicholas Renotte,308,"57,330.2",17657705,"57,330.2",17657705,130.1,40060
17,Rishabh Mishra,88,"184,760.7",16258940,"184,760.7",16258940,349.4,30746
18,Rob Mulla,157,"74,002.4",11618374,"74,002.4",11618374,83.8,13157
19,Ryan Nolan Data,154,"2,039.4",314062,"2,039.4",314062,7.5,1151
20,Socratica,661,"89,974.0",59472846,"89,974.0",59472846,79.9,52827
21,StatQuest with Josh Starmer,278,"236,140.1",65646950,"236,140.1",65646950,337.6,93856
22,Tableau Tim,508,"7,863.1",3994445,"7,863.1",3994445,11.2,5697
23,Thu Vu data analytics,86,"91,346.9",7855837,"91,346.9",7855837,111.6,9597
24,Tina Huang,220,"142,059.9",31253178,"142,059.9",31253178,215.0,47291
25,WsCube Tech,5158,"56,255.7",290166978,"56,255.7",290166978,40.4,208442
26,codebasics,876,"97,570.3",85471551,"97,570.3",85471551,93.7,82091
27,freeCodeCamp.org,1669,"432,369.5",721624649,"432,369.5",721624649,297.3,496224
28,sentdex,1254,"91,576.7",114837190,"91,576.7",114837190,108.3,135843
29,techTFQ,136,"122,410.1",16647771,"122,410.1",16647771,174.6,23740

In [33]:
channel_views=Channel_comparison.sort_values(by='view_mean',ascending=True)
channel_views.tail(10)

,Channel_Name,video_count,view_mean,view_count,Like_mean,Like_count,Comment_mean,Comment_count
0,Alex The Analyst,307,"114,871.2",35265444,"114,871.2",35265444,178.0,54633
29,techTFQ,136,"122,410.1",16647771,"122,410.1",16647771,174.6,23740
15,Luke Barousse,159,"139,121.3",22120289,"139,121.3",22120289,190.2,30246
24,Tina Huang,220,"142,059.9",31253178,"142,059.9",31253178,215.0,47291
10,Keith Galli,89,"170,584.2",15181994,"170,584.2",15181994,176.4,15703
17,Rishabh Mishra,88,"184,760.7",16258940,"184,760.7",16258940,349.4,30746
21,StatQuest with Josh Starmer,278,"236,140.1",65646950,"236,140.1",65646950,337.6,93856
27,freeCodeCamp.org,1669,"432,369.5",721624649,"432,369.5",721624649,297.3,496224
14,Leila Gharani,583,"434,039.8",253045182,"434,039.8",253045182,362.0,211057
12,Kevin Stratvert,854,"491,454.7",419702350,"491,454.7",419702350,382.6,326716

In [34]:
fig = px.bar(
    data_frame= channel_views.tail(10),
    orientation = "h",
    y = channel_views.tail(10).Channel_Name,
    x = channel_views.tail(10).view_mean,
    color = channel_views.tail(10).view_mean,

    labels = {"x": "average views", "y" : "Data Science YouTube channels"},
    title = "Top 10 Data Science YouTube channels with highest average views",
    text_auto= ".2s",
    template = "plotly_dark",
     color_continuous_scale=['#A084E8', '#00FFAB', '#00FFAB']
      )

update_layout(hover_bgcolor="#222", hover_font_size=14)

fig.update_traces(
    textposition = "outside",
    textfont = {
        "family": "tahoma",
         "size": 13,
    },
    hovertemplate= "Data Science YouTube channels: %{y}<br>average views: %{x:0.3s}"
)
iplot(fig)

In [35]:
channel_Like_mean=Channel_comparison.sort_values(by='Like_mean',ascending=False)
channel_Like_mean.head(10)

,Channel_Name,video_count,view_mean,view_count,Like_mean,Like_count,Comment_mean,Comment_count
12,Kevin Stratvert,854,"491,454.7",419702350,"491,454.7",419702350,382.6,326716
14,Leila Gharani,583,"434,039.8",253045182,"434,039.8",253045182,362.0,211057
27,freeCodeCamp.org,1669,"432,369.5",721624649,"432,369.5",721624649,297.3,496224
21,StatQuest with Josh Starmer,278,"236,140.1",65646950,"236,140.1",65646950,337.6,93856
17,Rishabh Mishra,88,"184,760.7",16258940,"184,760.7",16258940,349.4,30746
10,Keith Galli,89,"170,584.2",15181994,"170,584.2",15181994,176.4,15703
24,Tina Huang,220,"142,059.9",31253178,"142,059.9",31253178,215.0,47291
15,Luke Barousse,159,"139,121.3",22120289,"139,121.3",22120289,190.2,30246
29,techTFQ,136,"122,410.1",16647771,"122,410.1",16647771,174.6,23740
0,Alex The Analyst,307,"114,871.2",35265444,"114,871.2",35265444,178.0,54633

In [36]:
fig = px.bar(channel_Like_mean.head(10),
                 x = "Channel_Name",
                 y = "Like_mean",
                 color = "Channel_Name",
                 template = "plotly_dark",
                 color_discrete_sequence=["#45FFCA","#FF0060","#FF55BB", "#FFFDAF"],
                 opacity = 0.89,
                title = "Top 10 Data Science YouTube channels with highest average Likes")


update_layout(showlegend=True, hover_bgcolor="#222", hover_font_size=14)

fig.update_traces(
    textfont = {
        "family": "tahoma",
         "size": 13,
    },
    hovertemplate= "Channel_Name: %{x}<br>average Likes: %{y}"
)
iplot(fig)

In [37]:
channel_Comment_mean=Channel_comparison.sort_values(by='Comment_mean',ascending=True)
channel_Comment_mean.tail(10)

,Channel_Name,video_count,view_mean,view_count,Like_mean,Like_count,Comment_mean,Comment_count
29,techTFQ,136,"122,410.1",16647771,"122,410.1",16647771,174.6,23740
10,Keith Galli,89,"170,584.2",15181994,"170,584.2",15181994,176.4,15703
0,Alex The Analyst,307,"114,871.2",35265444,"114,871.2",35265444,178.0,54633
15,Luke Barousse,159,"139,121.3",22120289,"139,121.3",22120289,190.2,30246
24,Tina Huang,220,"142,059.9",31253178,"142,059.9",31253178,215.0,47291
27,freeCodeCamp.org,1669,"432,369.5",721624649,"432,369.5",721624649,297.3,496224
21,StatQuest with Josh Starmer,278,"236,140.1",65646950,"236,140.1",65646950,337.6,93856
17,Rishabh Mishra,88,"184,760.7",16258940,"184,760.7",16258940,349.4,30746
14,Leila Gharani,583,"434,039.8",253045182,"434,039.8",253045182,362.0,211057
12,Kevin Stratvert,854,"491,454.7",419702350,"491,454.7",419702350,382.6,326716

In [38]:
fig = px.scatter(channel_Comment_mean.tail(10),
                 y = "Channel_Name",
                 x = "Comment_mean",
                 size = "Comment_mean",
                 color = "Comment_mean",
                 template = "plotly_dark",
                 labels={"name" :"Data Science YouTube channels", "score" :"average comments"},
                 opacity = 0.89,
                title = "Top 10 Data Science YouTube channels with highest average comments",
                color_continuous_scale=['#A084E8', '#8BE8E5', '#00FFAB'])


update_layout(hover_bgcolor="#222", hover_font_size=14)

fig.update_traces(
    textfont = {
        "family": "tahoma",
         "size": 13,
    },
    hovertemplate= "YouTube channels: %{y}<br>average comments: %{x}"
)
iplot(fig)

<h3 style = "background-color: #010101;
             padding: 15px;
             font: bold 20px arial;
             color: gold;
             border: 2px solid tomato;
             border-radius: 8px">
♣ Now, will these 3 visuals we can notice some common youtube channels name we can say that probably they are the  <span style = "color: tomato">Best Data Science Educators</span> in The YouTube !! 👑🎬</h3>

#  Correlation

<h3 style = "background-color: #010101;
             padding: 18px;
             font: bold 24px arial;
             color: #45FFCA;
             border: 2px solid green;
             border-radius: 8px">
♣ Is There Any Correlation in the data set?!🎬</h3>

In [39]:
df_corr = Channel_comparison[["video_count", "view_mean",  "Like_mean", "Comment_mean"]]

In [40]:
df_corr.corr(numeric_only=True)

              video_count  view_mean  Like_mean  Comment_mean
video_count           1.0       -0.0       -0.0          -0.2
view_mean            -0.0        1.0        1.0           0.9
Like_mean            -0.0        1.0        1.0           0.9
Comment_mean         -0.2        0.9        0.9           1.0

In [41]:
# Create The Plotly Heat Map
fig = px.imshow(
    df_corr.corr(numeric_only = True),
    text_auto="0.2f", aspect="auto", template="plotly_dark",
    title="Correlation",
    color_continuous_scale = "earth"
)

update_layout(showlegend=True, hover_bgcolor="#222", hover_font_size=15)

fig.update_traces(
    textfont = {
        "family": "tahoma",
         "size": 16,
    },
    hovertemplate= "Feature[1]: %{x}<br>Feature[2]: %{y}"
)
iplot(fig)

<h3 style = "background-color: #000;
             padding: 18px;
             font: bold 20px tahoma;
             color: gold;
             border: 3px solid tomato;
             border-radius: 8px">
    ► From The HeatMap, We Can Say 😉🧐
    <BR><HR style = "border: 1px solid #555">
        1) There Is a Very Strong Positive Correlation Between <U>view_mean</U> and <U>Like_mean</U> (1.0)🔗..
    <BR>
        2) There Is a Strong Positive Correlation Between <U>view_mean</U> and <U>Comment_mean</U> (0.89)🔗
    

</h3>

In [42]:
fig = px.scatter(
    Channel_comparison,
    x = Channel_comparison["view_mean"],
    y = Channel_comparison["Like_mean"],
    trendline="ols",
    template="plotly_dark",
    color = Channel_comparison["Like_mean"],
    color_discrete_sequence=["#45FFCA"],
    title = "Relation Between Views & Likes",

          )

update_layout(showlegend=True, hover_bgcolor="#222", hover_font_size=15)
fig.update_traces(
    textfont = {
        "family": "tahoma",
         "size": 16,
    },
    hovertemplate= "Views: %{x:0.3s}<br>Likes: %{y:0.3s}"
)
iplot(fig)

In [43]:
fig = px.scatter(
    Channel_comparison,
    x = Channel_comparison["view_mean"],
    y = Channel_comparison["Comment_mean"],
    trendline="ols",
    template="plotly_dark",
    color = Channel_comparison["Comment_mean"],
    color_discrete_sequence=["#45FFCA"],
    title = "Relation Between Views & Comments",

          )

update_layout(showlegend=True, hover_bgcolor="#222", hover_font_size=15)
fig.update_traces(
    textfont = {
        "family": "tahoma",
         "size": 16,
    },
    hovertemplate= "Views: %{x:0.4s}<br>Comments: %{y:0.4s}"
)
iplot(fig)

# Now lets try to find best videos📺

In [44]:
df.sample(10)

,Channel_Name,Title,Published_date,Views,Like_count,Comment_Count
20032,freeCodeCamp.org,Django ChatGPT Clone Tutorial,2023-05-24,91828,91828,106
14601,Luke Barousse,Conditional Format Tables in Tableau (Like Exc...,2020-09-11,11495,11495,11
3765,Kevin Stratvert,"How to use Voice Typing in Windows, Microsoft ...",2023-05-31,128004,128004,164
11243,WsCube Tech,What are MySql Data Types - Explained with Exa...,2021-08-19,16668,16668,4
18884,Leila Gharani,How to Insert Cell Values into Footers and Hea...,2018-10-04,58653,58653,105
2553,Krish Naik,Feb 2 - Live Virtual Mock Interview Of Fresher...,2021-02-02,37192,37192,62
11490,WsCube Tech,How to Render an HTML Template as Response | D...,2021-06-27,112329,112329,78
1902,Krish Naik,I have Become A Recording Machine For Data Sci...,2022-11-01,16273,16273,97
11353,WsCube Tech,Digital Marketing Interview Questions and Answ...,2021-07-17,25795,25795,19
5846,ExcelIsFun,Excel Magic Trick 1217: D Functions: Text Crit...,2015-07-31,23365,23365,33

In [45]:
best_videos=df.sort_values(by=['Views', 'Like_count', 'Comment_Count'], ascending=True)
best_videos.tail(10)

,Channel_Name,Title,Published_date,Views,Like_count,Comment_Count
20547,freeCodeCamp.org,Introduction to Programming and Computer Scien...,2020-04-21,8255812,8255812,4095
20442,freeCodeCamp.org,Microsoft Excel Tutorial for Beginners - Full ...,2020-10-28,8998280,8998280,2446
17594,codebasics,Don't put toy dataset projects on your resume!,2024-03-22,9311413,9311413,541
20124,freeCodeCamp.org,Harvard CS50 – Full Computer Science Universit...,2022-10-19,11083884,11083884,7324
20872,freeCodeCamp.org,C Programming Tutorial for Beginners,2018-08-15,11353737,11353737,6674
20860,freeCodeCamp.org,C++ Tutorial for Beginners - Full Course,2018-08-24,12260170,12260170,11965
20720,freeCodeCamp.org,Learn JavaScript - Full Course for Beginners,2018-12-10,17075237,17075237,8540
20930,freeCodeCamp.org,SQL Tutorial - Full Database Course for Beginners,2018-07-02,18048065,18048065,11098
11210,WsCube Tech,Ethical HACKING Full Course in 10 HOURS (Begin...,2021-08-29,22003831,22003831,7772
20913,freeCodeCamp.org,Learn Python - Full Course for Beginners [Tuto...,2018-07-11,44191019,44191019,44314

In [46]:
fig = px.bar(
    data_frame=best_videos.tail(10),
    orientation="h",
    y=best_videos.tail(10).Title,
    x=best_videos.tail(10).Views,
    color=best_videos.tail(10).Views,
    labels={"x": "View,Likes and Comment", "y": "Videos"},
    title="Top 10 Videos on the basis of View,Likes and Comment",
    text_auto=".2s",
    template="plotly_dark",
    color_continuous_scale=['#FF5733', '#C70039', '#900C3F']
)
update_layout(hover_bgcolor="#222", hover_font_size=14)

fig.update_traces(
    textposition = "outside",
    textfont = {
        "family": "tahoma",
         "size": 13,
    },
    hovertemplate= "Videos: %{y}<br>AVG View: %{x:0.3s}"
)
iplot(fig)

<h3 style = "background-color: #111;
             padding: 15px;
             font: bold 18px arial;
             color: lightgreen;
             border: 2px solid lime;
             border-radius: 8px">
► These are the best video according to the audience .
<BR>