# Topics to include:-

**Evaluate a Model**

**precision**

**Hyperparameter**

**Balanced Bias-Variance**

**Overfitting and Underfitting**

**Cross-Validation**

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os

In [ ]:
import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/9394113857/Data-Sets/9882400f949ec59791995b8be588891f9e0daf48/spam.csv', delimiter=',', encoding='utf-8')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [ ]:
data.shape

(5572, 2)

In [ ]:
data

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
data.columns

Index(['Category', 'Message'], dtype='object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

**Dropped The Column Unnamed: 0**

In [ ]:
data.isna().sum()

Category    0
Message     0
dtype: int64

In [ ]:
data['Spam']=data['Category'].apply(lambda x:1 if x=='spam' else 0)
data.head(5)

  Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(data.Message,data.Spam,test_size=0.25)

In [ ]:
#CounterVectorizer Convert the text into matrics
from sklearn.feature_extraction.text import CountVectorizer

# Naive Bayes

**Naive Bayes Have three Classifier(Bernouli,Multinominal,Gaussian)
Here I use Multinominal Bayes Because here data in a discrete form
discrete data(e.g movie ratings ranging  1 to 5 as each rating will have certain frequency to represent)**

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
from sklearn.pipeline import Pipeline
clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

# Training The Model

In [ ]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

**Here I given Two email Two detect 1st One is looking good and the other one looking spam**

In [ ]:
emails=[
    'Sounds great! Are you home now?',
    'Will u meet ur dream partner soon? Is ur career off 2 a flyng start? 2 find out free, txt HORO followed by ur star sign, e. g. HORO ARIES'
]

**Predict Email**

In [ ]:
clf.predict(emails)

array([0, 1])

# Prediction Of Model

In [ ]:
clf.score(X_test,y_test)

0.9870782483847811

In [ ]:
emails = [
    'Sounds great! Are you home now?',
    'Will u meet ur dream partner soon? Is ur career off 2 a flyng start? 2 find out free, txt HORO followed by ur star sign, e. g. HORO ARIES'
]

# Predict the emails
predictions = clf.predict(emails)

# Display the predictions
for email, prediction in zip(emails, predictions):
    print(f"Email: {email}\nPrediction: {'Spam' if prediction == 1 else 'Not Spam'}\n")

Email: Sounds great! Are you home now?
Prediction: Not Spam

Email: Will u meet ur dream partner soon? Is ur career off 2 a flyng start? 2 find out free, txt HORO followed by ur star sign, e. g. HORO ARIES
Prediction: Spam

This code will predict whether the given emails are spam or not. It uses the trained clf model and displays the predictions accordingly.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

# Load the dataset
data = pd.read_csv('https://raw.githubusercontent.com/9394113857/Data-Sets/9882400f949ec59791995b8be588891f9e0daf48/spam.csv', delimiter=',', encoding='utf-8')

# Add a 'Spam' column
data['Spam'] = data['Category'].apply(lambda x: 1 if x == 'spam' else 0)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data.Message, data.Spam, test_size=0.25)

# Define the pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

# Train the model
clf.fit(X_train, y_train)

# Function to predict spam or not spam based on user input
def predict_spam():
    print("Enter an email message:")
    email = input("Email: ").strip()
    default_response = 'Sounds great! Are you home now?'  # Default placeholder

    if not email or email.lower() == 'yes':
        email = default_response

    prediction = clf.predict([email])
    result = "Spam" if prediction[0] == 1 else "Not Spam"
    print("Prediction:", result)

# Test the function
predict_spam()

Enter an email message:
Email: Will u meet ur dream partner soon? Is ur career off 2 a flyng start? 2 find out free, txt HORO followed by ur star sign, e. g. HORO ARIES
Prediction: Spam

In [ ]:
import joblib

# Save the trained model
joblib.dump(clf, 'spam_detection_model.pkl')

# Load the saved model
loaded_model = joblib.load('spam_detection_model.pkl')

# Function to predict spam or not spam based on user input using the loaded model
def predict_spam_loaded_model():
    print("Enter an email message:")
    email = input("Email: ").strip()
    default_response = 'Sounds great! Are you home now?'  # Default placeholder

    if not email or email.lower() == 'yes':
        email = default_response

    prediction = loaded_model.predict([email])
    result = "Spam" if prediction[0] == 1 else "Not Spam"
    print("Prediction:", result)

# Test the function with the loaded model
predict_spam_loaded_model()

Enter an email message:
Email: Will u meet ur dream partner soon? Is ur career off 2 a flyng start? 2 find out free, txt HORO followed by ur star sign, e. g. HORO ARIES
Prediction: Spam

# Here's how you can download the model file:

In [ ]:
import gdown
import os
from rich.console import Console
from rich.text import Text

# Initialize a Console object for rich output
console = Console()

# Define the file ID for the file you want to download from Google Drive
file_id = '17pBC9z_mIqnaHewJMic6KJIa5yrWwraO'

# Ask the user for the file name to save the downloaded file as
# Provide a default file name ('spam_detection_model.pkl') if the user doesn't input anything
output_path = input("Enter the name to save the file (press Enter to use default 'spam_detection_model.pkl'): ")

# If no input is provided, use the default output file name
if not output_path:
    output_path = 'spam_detection_model.pkl'  # Default file name

# **Separated Output for Clear Visibility**
console.print("\n" + "-" * 60)  # Separator for clarity
console.print(f"[bold cyan]The file will be saved as: [bold green]{output_path}[/bold green][/bold cyan]")
console.print("-" * 60)  # Another separator for better structure

# Check if the file already exists
if os.path.exists(output_path):
    console.print(f"\n[bold yellow]The file [bold green]{output_path}[/bold green] already exists. Skipping download.[/bold yellow]")
    console.print("-" * 60)  # Separator after the message
else:
    # Informing the user about the download process
    console.print(f"\n[bold yellow]Starting download... Please wait.[/bold yellow]", style="bold")
    console.print("-" * 60)  # Separator for better visual structure

    try:
        # Use gdown to download the file from Google Drive
        gdown.download(f'https://drive.google.com/uc?id={file_id}', output_path, quiet=False)

        # Notify the user upon successful download
        console.print(f"\n[bold green]Download complete![/bold green] The file is saved as [bold green]{output_path}[/bold green].", style="bold")
        console.print("-" * 60)  # Final separator for better separation

    except Exception as e:
        # If there's an error, show a clear error message
        console.print(f"\n[bold red]Error:[/bold red] An error occurred while downloading the file: {e}", style="bold")
        console.print("-" * 60)  # Separator after error message

Enter the name to save the file (press Enter to use default 'spam_detection_model.pkl'):

------------------------------------------------------------

The file will be saved as: spam_detection_model.pkl

------------------------------------------------------------

The file spam_detection_model.pkl already exists. Skipping download.

------------------------------------------------------------

In [ ]:
import os  # Importing the os module to run system commands like installing packages

# Try to import the 'rich' library, which is used to create rich text and tables in the console
try:
    import rich
    print("Rich module is already installed.")  # Print if the 'rich' module is successfully imported
except ImportError:
    # If the 'rich' module is not found, the code enters this block
    print("Rich module not found, installing...")  # Print that the module is not installed and will be installed
    os.system('pip install rich')  # Run the system command to install the 'rich' module using pip
    print("Installation of 'rich' completed. Please rerun the script.")  # Print a message indicating installation completion
    exit()  # Exit the script after installing 'rich', as the script needs to be rerun after installation

Rich module is already installed.

# After downloading the model file, you can load it and make predictions using the following code:

**Sample Inputs for Spam:**
1.	"You won the campaign! Please give your address to send a gift voucher to your address."
2.	"Congratulations! You've been selected for a free prize! Click the link to claim it now!"
3.	"Limited time offer! Get a free iPhone now, just pay shipping fees. Act fast!"
4.	"URGENT: Your account has been compromised. Log in immediately to secure your information."
5.	"Exclusive offer for you! Get a $1000 Amazon gift card by filling out a quick survey."
6.	"Hi! You’re eligible for a large cash prize, just send us your bank details to claim it!"
7.	"Final notice! Your package is waiting for you. Click here to schedule delivery."
8.	"You've won a lottery! Send your details to claim your reward."

**Sample Inputs for Not Spam:**
1.	"Hey, I just wanted to check in to see if we are still meeting at 2 pm tomorrow?"
2.	"Are we still on for lunch at 1 pm? Let me know if the time works for you!"
3.	"Please send me the report when you get a chance. Thanks!"
4.	"Just wanted to confirm that the meeting is scheduled for 3 pm today."
5.	"Looking forward to our collaboration next week. Let me know if there's anything I should prepare!"
6.	"I really enjoyed our conversation today. Looking forward to meeting again soon!"
7.	"Please review the attached file and let me know if you have any feedback."
8.	"Do you want to grab coffee later? Let me know when you're free!"

**Explanation of Input Categories:**

•	**Spam:** These types of messages usually contain offers that seem too good to be true, require personal or financial information, or create a sense of urgency or threat (e.g., fake prizes, phishing attempts).

•	**Not Spam:** These are normal personal or professional emails that don't ask for personal information, nor do they offer unrealistic prizes or create urgency in a manipulative way.
You can use these samples to test your spam detection model, as they cover typical spam and non-spam scenarios.

In [ ]:
import joblib
import os
from rich.console import Console
from rich.table import Table
from rich import box  # Importing box styles
from datetime import datetime
import pytz
import warnings

# Suppress any warnings
warnings.filterwarnings("ignore", category=UserWarning)

# List all files in the current directory and filter out the model files
def list_model_files():
    files = [f for f in os.listdir() if f.endswith('.pkl')]
    return files

# Automatically detect available model file(s)
model_files = list_model_files()

# If no model file is found, exit
if not model_files:
    print("Error: No model files found in the current directory.")
    exit()

# If only one model file is found, use it automatically
if len(model_files) == 1:
    default_model_name = model_files[0]
    print(f"Using default model file: {default_model_name}")

# If multiple model files are found, prompt the user to select one
else:
    print("Multiple model files found:")
    for i, model in enumerate(model_files, start=1):
        print(f"{i}. {model}")

    # Ask the user to select a model
    try:
        choice = int(input(f"\nEnter the number corresponding to the model you want to use (1-{len(model_files)}): "))
        if 1 <= choice <= len(model_files):
            default_model_name = model_files[choice - 1]
            print(f"Using selected model file: {default_model_name}")
        else:
            print("Invalid choice. Exiting.")
            exit()
    except ValueError:
        print("Invalid input. Exiting.")
        exit()

# Try to load the model file
try:
    loaded_model = joblib.load(default_model_name)
except Exception as e:
    print(f"Error loading the model: {e}")
    exit()  # Exit if the model couldn't be loaded

# Function to get current time in IST and formatted date/time string
def get_current_time_ist():
    ist = pytz.timezone('Asia/Kolkata')  # Set IST timezone
    now_ist = datetime.now(ist)  # Get the current time in IST
    formatted_date_time = now_ist.strftime('%Y-%m-%d %H:%M:%S')  # Format the date and time
    return formatted_date_time

# Function to predict spam or not spam based on user input using the loaded model
def predict_spam_loaded_model():
    console = Console()

    # Get current time for displaying
    current_time = get_current_time_ist()

    # Direct and simple email message input prompt with extra line breaks for clarity
    console.print("\n[bold magenta on white] Enter an Email Message to Check Spam Status: [/bold magenta on white]")
    email = input().strip()  # Get user input directly

    # Default response in case of empty input
    default_response = 'Sounds great! Are you home now?'

    # If the input is empty or contains only 'yes', use the default message
    if not email or email.lower() == 'yes':
        email = default_response

    # Add spacing before displaying the user input
    console.print(f"\n[bold cyan]User Input:[/bold cyan] [italic yellow]{email}[/italic yellow]", style="bold")
    console.print("\n" + "-" * 60)  # Separator for better visual structure

    # Display current time of execution in the output
    console.print(f"[bold green]Execution Time: {current_time}[/bold green]")
    console.print("\n" + "-" * 60)  # Separator for better visual structure

    # Make a prediction using the loaded model
    prediction = loaded_model.predict([email])

    # Interpret the result
    result = "Spam" if prediction[0] == 1 else "Not Spam"

    # Add some space before showing prediction result
    console.print(f"\n[bold blue on white]Prediction Result:[/bold blue on white] [bold red]{result}[/bold red]\n")
    console.print("\n" + "-" * 60)  # Separator for better visual structure

    # Create and style the result table with more separation and better alignment
    table = Table(title="[bold green]Spam Detection Result[/bold green]", box=box.ROUNDED, show_header=True)

    # Adding styled columns with clear text alignment and space between them
    table.add_column("Email Message", style="bold white", justify="center", width=40)
    table.add_column("Prediction", style="bold yellow", justify="center", width=20)

    # Add the email message and prediction to the table
    table.add_row(email, result)

    # Print the result in a well-formatted table with extra spacing
    console.print("\n" + "-" * 60)  # Final separator
    console.print(table)

# Test the function with the loaded model
predict_spam_loaded_model()

Using default model file: spam_detection_model.pkl

 Enter an Email Message to Check Spam Status:

Do you want to grab coffee later? Let me know when you're free!

User Input: Do you want to grab coffee later? Let me know when you're free!

------------------------------------------------------------

Execution Time: 2024-12-16 11:51:04

------------------------------------------------------------

Prediction Result: Not Spam

------------------------------------------------------------

------------------------------------------------------------

                       Spam Detection Result
╭──────────────────────────────────────────┬──────────────────────╮
│              Email Message               │      Prediction      │
├──────────────────────────────────────────┼──────────────────────┤
│ Do you want to grab coffee later? Let me │       Not Spam       │
│          know when you're free!          │                      │
╰──────────────────────────────────────────┴──────────────────────╯

In [ ]:
import pandas as pd

# Creating a DataFrame to present information in table format
spam_detection_summary_table = pd.DataFrame(columns=['SNo', 'Type', 'Task', 'Target Variable', 'Data Type'])

# Adding information for the spam email detection problem
spam_detection_summary_table.loc[0] = [1, 'Supervised Learning', 'Binary Classification', 'Spam Email', 'Text Data']

# Displaying the information in table format
print(spam_detection_summary_table.to_markdown(index=False, tablefmt="pretty", colalign=("center",)))

+-----+---------------------+-----------------------+-----------------+-----------+
| SNo |        Type         |         Task          | Target Variable | Data Type |
+-----+---------------------+-----------------------+-----------------+-----------+
|  1  | Supervised Learning | Binary Classification |   Spam Email    | Text Data |
+-----+---------------------+-----------------------+-----------------+-----------+

# ChatGPT Link:-

**Chat about this code only.**

In [ ]:
# https://chat.openai.com/c/66fee768-f54a-4bd3-8d2a-70e6e78099b1

In [ ]:
# Track the time when the last cell is executed
last_cell_time = datetime.now()

# Get current time in IST for the last cell entry
now_ist_last = datetime.now(ist)

# Format the current date and time for the last cell
formatted_date_last = now_ist_last.strftime('%Y-%m-%d')
formatted_time_last = now_ist_last.strftime('%H:%M:%S %Z%z')

# Display the statement "All cells above have been executed..." in red and bold
display(HTML("<p style='color:red; font-weight:bold;'>All cells above have been executed. Below is the current date and time in IST:</p>"))

# Display the last cell entry time in bold (default color)
display(Markdown(f'**Last Cell Entry Time: {formatted_date_last} {formatted_time_last}**'))

NameError: name 'datetime' is not defined

In [ ]:
# Calculate the time difference between first and last cell execution
time_diff = last_cell_time - first_cell_time

# Extract hours, minutes, and seconds from the time difference
hours = time_diff.seconds // 3600  # Total seconds divided by 3600 to get hours
minutes = (time_diff.seconds % 3600) // 60  # Remainder divided by 60 to get minutes
seconds = time_diff.seconds % 60  # Remainder gives the number of seconds

# Display the statement for total time taken in execution in orange and bold
display(HTML("<p style='color:orange; font-weight:bold;'>Total Time Taken for Notebook Execution:</p>"))

# Display the first and last cell entry times along with the total time taken in HH:MM:SS format
display(Markdown(f'**First Cell Entry Time: {current_time_ist_first}**'))
display(Markdown(f'**Last Cell Entry Time: {formatted_date_last} {formatted_time_last}**'))
display(Markdown(f'**Time Taken: {hours} hour(s), {minutes} minute(s), and {seconds} second(s)**'))

# Interview Preparation Notes

Here are some potential interview questions and answers based on the concepts covered in this notebook:

**Q1: What is the main task being performed in this notebook?**
A1: The main task is building a spam email detection model using machine learning.

**Q2: What type of machine learning problem is spam detection considered?**
A2: Spam detection is a supervised learning problem, specifically binary classification, where the goal is to classify emails into one of two categories: "spam" or "not spam".

**Q3: What dataset is being used for this task?**
A3: The notebook uses a dataset containing email messages and their corresponding categories ('spam' or 'ham'), loaded from a CSV file hosted on GitHub.

**Q4: What is the purpose of the 'Spam' column created in the DataFrame?**
A4: The 'Spam' column is a numerical representation of the 'Category' column, where 'spam' is mapped to 1 and 'ham' (not spam) is mapped to 0. This is done to prepare the data for the machine learning model, which typically works with numerical inputs.

**Q5: How is the data split for training and testing the model?**
A5: The data is split into training and testing sets using `train_test_split` from scikit-learn. 25% of the data is allocated for testing (`test_size=0.25`).

**Q6: What technique is used to convert the text data (email messages) into a format suitable for the machine learning model?**
A6: The `CountVectorizer` from scikit-learn is used to convert the text data into a matrix of token counts. This represents each email as a numerical vector based on the frequency of words.

**Q7: Which machine learning algorithm is used for classification in this notebook? Why was this specific type of Naive Bayes classifier chosen?**
A7: A Multinomial Naive Bayes classifier (`MultinomialNB`) is used. This type is suitable for discrete data like word counts, which are generated by the `CountVectorizer`.

**Q8: Explain the role of the `Pipeline` in this notebook.**
A8: The `Pipeline` is used to chain multiple steps together, specifically the `CountVectorizer` (text vectorization) and the `MultinomialNB` classifier (model training). This simplifies the workflow and ensures that the same preprocessing steps are applied consistently to both the training and testing data.

**Q9: How is the trained model saved and loaded?**
A9: The `joblib` library is used to save the trained model to a file (`spam_detection_model.pkl`) and load it back later. This allows for reusing the trained model without retraining.

**Q10: How can you evaluate the performance of the trained model?**
A10: The notebook uses the `score()` method of the trained pipeline (`clf.score(X_test, y_test)`) to evaluate the model's accuracy on the test set.

**Q11: What is the significance of the sample inputs provided for spam and not spam emails?**
A11: The sample inputs demonstrate typical examples of spam and non-spam emails, which can be used to test the model's predictions and understand its behavior in different scenarios.

**Q12: What are some potential next steps or improvements that could be made to this spam detection model?**
A12: Potential improvements could include:
1.  Trying different text vectorization techniques (e.g., TF-IDF).
2.  Experimenting with other classification algorithms (e.g., Support Vector Machines, Logistic Regression, Deep Learning models).
3.  Performing more extensive data preprocessing (e.g., removing stop words, stemming, lemmatization).
4.  Evaluating the model using other metrics like precision, recall, and F1-score, which are particularly important for imbalanced datasets like spam detection.
5.  Implementing cross-validation for more robust model evaluation.
6.  Hyperparameter tuning to optimize the model's performance.